I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/venaprologue.rpy", line 39, in script
    pause 500
  File "renpy/common/000statements.rpy", line 453, in execute_pause
    renpy.pause(delay)
TypeError: 'Dissolve' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/venaprologue.rpy", line 39, in script
    pause 500
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 453, in execute_pause
    renpy.pause(delay)
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\exports.py", line 1533, in pause
    rv = renpy.ui.interact(mouse='pause', type='pause', roll_forward=roll_forward, pause=delay)
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\display\core.py", line 3377, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\Users\Beste\Documents\renpy-8.0.1-sdk\renpy\display\core.py", line 3741, in interact_core
    trans = self.ongoing_transition[None](
TypeError: 'Dissolve' object is not callable

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.1.22070801
The Calling 1.0
Wed Aug  3 23:26:39 2022
