I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 173, in script
    show screen ctc()
  File "renpy/common/000statements.rpy", line 549, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
Exception: Screen ctc is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 173, in script
    show screen ctc()
  File "renpy/ast.py", line 1969, in execute
    self.call("execute")
  File "renpy/ast.py", line 1957, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "renpy/statements.py", line 278, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 549, in execute_show_screen
    renpy.show_screen(name, *args, **kwargs)
  File "renpy/display/screen.py", line 1114, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen ctc is not known.


Windows-10-10.0.22598
Ren'Py 7.4.4.1439
The Calling 1.0
Sat Apr 16 21:25:20 2022
